### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by cbettemb** [askomics/askomics#103]
Hi,

The new administration features seems really nice, however I can't sign up. Clicking on the Sign up button does nothing (nothing is logged in the AskOmics console nor in the browser console). I didn't receive any mail either. Are there some extra requirement regarding a smtp server to set up or something else? Is there a default admin account?

Thanks,
Charles

**Comment by cbettemb** [comment]
That's strange but the account creation actually worked, but I had to shut down askomics to effectively create the account, which is administrator. I don't know if it is caused by my environment.

**Comment by ofilangi** [comment]
there are something new in the config :
# SMTP Server
smtp.host=Sphinx
otherwise, the first account is the admin account. maybe the behaviours is strange the first time without refresh the browser...

xgaia could say more...
