### ISSUE TITLE
I want to be able to delete a relation

### ISSUE THREAD

**Issue by abretaud** [askomics/askomics#162]

**Comment by xgaia** [comment]
hello @abretaud, can you specify your problem ?

**Comment by abretaud** [comment]
It's hard, I don't remember what I meant...

**Comment by xgaia** [comment]
:clap:

**Comment by abretaud** [comment]
I guess I wanted to delete a relation.

**Comment by xgaia** [comment]
On the askomics graph, if you want to delete a relation between 2 nodes, you can click on a node and delete it. It will delete the relation
