### ISSUE TITLE
support for xsd:date (and xsd:datetime?)

### ISSUE THREAD

**Issue by odameron** [askomics/askomics#186]
It would be helpful if xsd:date (https://www.w3.org/TR/xmlschema-2/#date) and maybe xsd:dateTime (https://www.w3.org/TR/xmlschema-2/#dateTime) were supported in the dropdown list when integrating files.

Automatic guess definitely not a priority

**Comment by sletort** [comment]
Uniprot integration need xsd:date also.
Please reopen this issue.
