### ISSUE TITLE
wrong sparql translation of "absent relation" contraint

### ISSUE THREAD

**Issue by odameron** [askomics/askomics#208]
If I want to retrieve all the instances of `A` that are not associated to any instance of `B` through the `rel` relation, I:

- select `A`
- follow the `rel` arrow and select `B`
- left-click on the `rel` arrow and check the 'absent relation' checkbox
- hide `B` so as not to see all the `B` that are not associated to `A` (by the way, should'nt this be automated when checking the 'absent relation' checkbox?)

The generated sparql query is similar to:
```
SELECT ?a
WHERE {
  ?a rdf:type :A .
  ?b rdf:type :B .
  FILTER NOT EXISTS {
    ?a :rel ?b .
  }
}
```

I believe it should be

```
SELECT ?a
WHERE {
  ?a rdf:type :A .
  FILTER NOT EXISTS {
    ?b rdf:type :B .
    ?a :rel ?b .
  }
}
```

**Comment by ofilangi** [comment]
I agree with that. In fact the old functionnality would have the name 'negative relation'. but this information is not really interesting.
so, as you propose, we can 1) undisplay the object entity and 2) integrate the object entity inside the filter.
