### ISSUE TITLE
Querying is still possible after deleting everything

### ISSUE THREAD

**Issue by sletort** [askomics/askomics#248]
maybe i misunderstand the way how askomics works.
I deleted all files in the "uploaded file" page, but in the querying page i still have access to my data.

I just saw that I can delete the dataset from the page "tools-> Datasets"

**Comment by xgaia** [comment]
Hello @sletort,

The "uploaded files" page show the text/gff/ttl files you upload to the server.
In the "Tools > Datasets" represent the integrated data in the triplesore.

So when you delete the uploaded files, Data are still in the triplestore. If you want to delete them, you must indeed use "tools >datasets".

**Comment by sletort** [comment]
thanks for the explanations.
