### ISSUE TITLE
I propose to remove class SparqlQuery

### ISSUE THREAD

**Issue by sletort** [askomics/askomics#309]
[//]: # (Check the boxes corresponding to your situation: [x])
 [//]: # (Replace XX.XX with the version)

I have installed AskOmics with:
- [ ] git
- [ ] docker
- [ ] askomics-docker-compose repository
- [ ] No idea
- [X] VM

I Installed virtuoso from:
- [ ] Compiled from sources
- [ ] docker
- [ ] askomics-docker-compose repository
- [X] No idea

The deployment mode of AskOmics is:
- [x] dev
- [ ] prod
- [ ] No idea

The AskOmics version is:
- [x] The master branch
- [ ] A specific version: XX.XX
- [ ] No idea

[//]: # (Describe your problem/suggestion here)

SparqlQuery is a class that contains only the query string, no method, no other attribute.
I think it is useless.

[//]: # (Post some log if you can have)

**Comment by xgaia** [comment]
I agree
