### ISSUE TITLE
Initial Virtuoso system parameters

### ISSUE THREAD

**Issue by jpvernadet** [askomics/askomics#87]
Is it possible to increase the value of MaxQueryCostEstimationTime and MaxQueryExecutionTime in initial system parameters of Virtuoso ? It failed with 300 to integrate data file or request. I tried 3000 on both and it worked.

**Comment by ofilangi** [comment]
this is a parameter of the tenforce/virtuoso :
 VIRT_Parameters_NumberOfBuffers: 510000
            VIRT_Parameters_MaxDirtyBuffers: 375000
            VIRT_Parameters_TN_MAX_memory: 4000000000
            VIRT_SPARQL_ResultSetMaxRows: 100000
            VIRT_SPARQL_MaxQueryCostEstimationTime: 300
            VIRT_SPARQL_MaxQueryExecutionTime: 300
            VIRT_SPARQL_MaxDataSourceSize: 1000000000
            VIRT_Flags_TN_MAX_memory: 4000000000
have a look on https://hub.docker.com/r/tenforce/virtuoso/ and https://github.com/askomics/askomics-docker-compose/
